### ISSUE TITLE
Document sources and build method

### ISSUE THREAD

**Issue by varac** [ms-jpq/coq.artifacts#20]
First of all, thanks a lot for coq + all the snippets !
Could you please document how these snippets are gathered and built ? 
I.e. which sources you use, and publish the built script (are doing this manual / via some gh action etc) ?

**Comment by varac** [comment]
Hugh, just found a lead at https://github.com/ms-jpq/coq_nvim/blob/coq/config/compilation.yml, is this the comlete list of sources this repo is built from ?

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/tree/coq/coq/ci

**Comment by ms-jpq** [comment]
those two manly
